server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: slk-ms
  redis:
    host: 127.0.0.1
    port: 10231
    password: root
    timeout: 2000

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"